### ISSUE TITLE
Multipart::FormData::Generator#field gives empty body when passed an Int as value

### ISSUE THREAD

**Issue by NightFeather** [RX14/multipart.cr#7]
IO::Memory.new also provides a version which accepts an Int for size,
that will give us an empty body part (not what we expected).

**Comment by RX14** [comment]
You shouldn't be using this shard - its been merged into the stdlib for quite a few versions. The same bug does exist in the stdlib however - we should call to_s on the object passed in.

**Comment by straight-shoota** [comment]
@RX14 Maybe add a note about this in the README? Possibly remove files from src in master branch to let people know they shouldn't use this?

**Comment by RX14** [comment]
Yep, I was planning on doing that but got distracted.

**Comment by RX14** [comment]
Done!
